baseURL: https://attila.fejer.io/
languageCode: en-us
title: Attila Fejér Portfolio
theme: toha

enableEmoji: true

languages:
  en:
    languageName: English
    weight: 1

params:
  gitRepo: https://github.com/hugo-toha/hugo-toha.github.io
  enableBlogPost: false
  enableTOC: false
  newsletter:
    enable: false
