baseURL: https://gearoid.otreasaigh.com/
languageCode: en-gb
title: Gearóid Ó Treasaigh
theme: toha

googleAnalytics: G-41SK9G84HV

enableEmoji: true

languages:
  en:
    languageName: English
    weight: 1

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  background: /images/site/background.png
  logo:
    favicon: /images/author/gearoid.png
  gitRepo: https://github.com/hugo-toha/hugo-toha.github.io

  topNavbar:
    maxVisibleSections: 7

  darkMode:
    enable: true
    provider: darkreader
    default: system

  features:
    portfolio:
      enable: true
    blog:
      enable: false
    notes:
      enable: false
    comment:
      enable: false
    analytics:
      enabled: true
      services:
        google:
          id: G-41SK9G84HV
    support:
      enable: false
      services:
        kofi:
          user: hossainemruz
          text: Tip Me
          textColor: '#f9fafc'
          backgroundColor: '#248aaa'
        # buymeacoffee:
        #   user: <your buymeacoffee.com user>
        #   text: Support me on Buy me a coffee!
        #   info: Buy me a coffee!
        #   color: '#FFDD00'
    toc:
      enable: false
    tags:
      enable: false
    flags:
      enable: true
    embedpdf:
      enable: false
    flowchart:
      enable: false
    math:
      enable: false
    syntaxHighlight:
      enable: false
    videoPlayer:
      enable: false

  footer:
    enable: true
    navigation:
      enable: true
      customMenus: true
    contactMe:
      enable: true
    credentials:
      enable: true
    newsletter:
      enable: false
    disclaimer:
      enable: false

  minify:
    minifyOutput: true
