[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.115.0"

[context.production]
  command = "hugo -b https://gearoid.otreasaigh.com --minify"

[context.deploy-preview]
  command = "hugo -b $gp_PRIME_URL --minify"
