name: Auto Merge Dependabot PRs

on:
  pull_request_target:

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Check out to get the configuration file .github/auto-merge.yml
        uses: actions/checkout@v5

      - name: 🤖 DependaBot AutoMerge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.DEPENDABOT }}
          command: merge
